version: '3'

services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SECRET_KEY: ${SECRET_KEY}
    restart: always
